#!/bin/bash

echo "🔧 GitHub Push Helper"
echo "===================="
echo ""
echo "The repository URL you're trying to use is:"
echo "https://github.com/edu2medu/edu2medu.git"
echo ""
echo "Common issues and solutions:"
echo ""
echo "1. If the repository name or username is different:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo ""
echo "2. If you need to authenticate:"
echo "   - Use Personal Access Token (not password)"
echo "   - Or use SSH: git remote add origin git@github.com:USERNAME/REPO.git"
echo ""
echo "3. To check if repository exists, visit:"
echo "   https://github.com/edu2medu/edu2medu"
echo ""
echo "Ready to push? Run these commands:"
echo ""
echo "# Step 1: Remove old remote (if exists)"
echo "git remote remove origin"
echo ""
echo "# Step 2: Add correct remote (replace with your actual repo URL)"
echo "git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo ""
echo "# Step 3: Push to GitHub"
echo "git push -u origin main"
echo ""
echo "If authentication fails, you'll need a Personal Access Token:"
echo "1. Go to GitHub → Settings → Developer settings → Personal access tokens"
echo "2. Generate new token (classic)"
echo "3. Select 'repo' scope"
echo "4. Copy token and use it as password when pushing"

